### ISSUE TITLE
Cannot read property 'Rows' of undefined

### ISSUE THREAD

**Issue by jlopes90** [dcmjs-org/dcmjs#211] opened 2021-07-09 14:11 UTC
Create and read RLE encoded DICOM Segmentation with Cornerstone
Example: https://dcmjs.netlify.app/createsegmentationrleroundtrip/

![image](https://user-images.githubusercontent.com/50026015/125090580-63a7ff00-e0c7-11eb-8e3e-6853c560ef42.png)

![image](https://user-images.githubusercontent.com/50026015/125089997-c77df800-e0c6-11eb-8fb6-43e1e13b8137.png)

Display DICOM Segmentation with Cornerstone
Example: https://dcmjs.netlify.app/displaysegmentation/

![image](https://user-images.githubusercontent.com/50026015/125090857-bb466a80-e0c7-11eb-9341-cd7505dce461.png)

![image](https://user-images.githubusercontent.com/50026015/125090900-c9948680-e0c7-11eb-881a-ec911d174f75.png)

**Comment by pieper** [comment] 2021-07-09 15:06
Thanks for reporting this, I'm able to reproduce it.  My guess is that something has changed in cornerstone or else this version of the segmentation example isn't working for some reason (I know earlier versions did).  I appreciate any help you can provide troubleshooting this to fix the example, maybe by reverting versions of this code or cornerstone.

If you want more fully worked out solution you can look at OHIF, for example ([here](https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571?seriesInstanceUID=1.2.276.0.7230010.3.1.3.0.57823.1553343864.578877,1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680))

**Comment by fedorov** [comment] 2021-07-09 16:10
Steve, did we test OHIF with RLE-encoded SEGs? Those I know of are just bit-packed, not RLE encoded.

**Comment by pieper** [comment] 2021-07-09 16:39
Good point, this example is from @JamesAPetts to do RLE.  So I can't actually say.  I hope he's able to confirm that this did work when committed and maybe that will give a clue about why it might not be working now.

**Comment by JamesAPetts** [comment] 2021-07-15 13:12
Hey, yeah this demo worked when it was built.

I don't think it reflects commonly available data though, its RLE with the liberal abuse of FRACTIONAL SegmentationType to make files with many segments (e.g. Freesurfer segmentations) as small as possible, as these didn't scale well with binary due to their being loads and loads of zeroes per segment frame.

I don't think we ended up using it anywhere yet to build examples, hence the "create-and-read" demo.

**Comment by jlopes90** [comment] 2022-11-07 23:47
There is another solution:

Is to ignore "sourceImageMetadata".

Before:
https://github.com/dcmjs-org/dcmjs/blob/c209047861d2ef6c17526c6d1e29d5db7e895b29/src/adapters/Cornerstone/Segmentation_4X.js#L936-L949

After:
```javascript
/* const sourceImageMetadata = metadataProvider.get( 
   "instance", 
   imageId 
); 
if ( 
   Rows !== sourceImageMetadata.Rows || 
   Columns !== sourceImageMetadata.Columns 
) { 
   throw new Error( 
       "Individual SEG frames have different geometry dimensions (Rows and Columns) " + 
           "respect to the source image reference frame. This is not yet supported. " + 
           "Aborting segmentation loading. " 
   ); 
} */
```

I've already tested my platform and it works export and import segmentation.

**Closed** 2023-10-10 23:18 UTC
